/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fornecedores;

/**
 *
 * @author Windows
 */
public class AddFornecedorFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddFornecedorFrame
     */
    public AddFornecedorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelSalmxLogo = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPass1 = new javax.swing.JLabel();
        jLabelUserName1 = new javax.swing.JLabel();
        jTextFieldUser1 = new javax.swing.JTextField();
        jLabelUserName2 = new javax.swing.JLabel();
        jLabelUserName3 = new javax.swing.JLabel();
        jTextFieldUser3 = new javax.swing.JTextField();
        jTextFieldUser4 = new javax.swing.JTextField();
        jTextFieldUser5 = new javax.swing.JTextField();
        jTextFieldUser6 = new javax.swing.JTextField();
        jTextFieldUser7 = new javax.swing.JTextField();
        jLabelUserName4 = new javax.swing.JLabel();
        jTextFieldUser8 = new javax.swing.JTextField();
        jLabelUserName5 = new javax.swing.JLabel();
        jTextFieldUser9 = new javax.swing.JTextField();
        jLabelUserName6 = new javax.swing.JLabel();
        jTextFieldUser2 = new javax.swing.JTextField();
        jLabelUserName7 = new javax.swing.JLabel();
        jTextFieldUser10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTop.setBackground(new java.awt.Color(255, 102, 102));

        jLabelSalmxLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSalmxLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalmxLogoPequeno.png"))); // NOI18N
        jLabelSalmxLogo.setText(" ");
        jLabelSalmxLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jPanelBody.setBackground(new java.awt.Color(242, 242, 242));

        jLabelUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName.setText("Telefone");

        jLabelPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 102, 102));
        jLabelPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPass.setText("Inscrição Estadual");

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALVAR");
        jLabel1.setOpaque(true);

        jLabelPass1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPass1.setForeground(new java.awt.Color(255, 102, 102));
        jLabelPass1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPass1.setText("CNPJ");

        jLabelUserName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName1.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName1.setText("Rua");

        jTextFieldUser1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser1.setText(" ");
        jTextFieldUser1.setToolTipText("");
        jTextFieldUser1.setAutoscrolls(false);
        jTextFieldUser1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser1ActionPerformed(evt);
            }
        });

        jLabelUserName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName2.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName2.setText("Numero");

        jLabelUserName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName3.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName3.setText("Bairro");

        jTextFieldUser3.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser3.setText(" ");
        jTextFieldUser3.setToolTipText("");
        jTextFieldUser3.setAutoscrolls(false);
        jTextFieldUser3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser3ActionPerformed(evt);
            }
        });

        jTextFieldUser4.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser4.setText(" ");
        jTextFieldUser4.setToolTipText("");
        jTextFieldUser4.setAutoscrolls(false);
        jTextFieldUser4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser4ActionPerformed(evt);
            }
        });

        jTextFieldUser5.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser5.setText(" ");
        jTextFieldUser5.setToolTipText("");
        jTextFieldUser5.setAutoscrolls(false);
        jTextFieldUser5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser5ActionPerformed(evt);
            }
        });

        jTextFieldUser6.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser6.setText(" ");
        jTextFieldUser6.setToolTipText("");
        jTextFieldUser6.setAutoscrolls(false);
        jTextFieldUser6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser6ActionPerformed(evt);
            }
        });

        jTextFieldUser7.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser7.setText(" ");
        jTextFieldUser7.setToolTipText("");
        jTextFieldUser7.setAutoscrolls(false);
        jTextFieldUser7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser7ActionPerformed(evt);
            }
        });

        jLabelUserName4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName4.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName4.setText("Cidade");

        jTextFieldUser8.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser8.setText(" ");
        jTextFieldUser8.setToolTipText("");
        jTextFieldUser8.setAutoscrolls(false);
        jTextFieldUser8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser8ActionPerformed(evt);
            }
        });

        jLabelUserName5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName5.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName5.setText("UF");

        jTextFieldUser9.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser9.setText(" ");
        jTextFieldUser9.setToolTipText("");
        jTextFieldUser9.setAutoscrolls(false);
        jTextFieldUser9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser9ActionPerformed(evt);
            }
        });

        jLabelUserName6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName6.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName6.setText("Razão Social");

        jTextFieldUser2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser2.setText(" ");
        jTextFieldUser2.setToolTipText("");
        jTextFieldUser2.setAutoscrolls(false);
        jTextFieldUser2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser2ActionPerformed(evt);
            }
        });

        jLabelUserName7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserName7.setForeground(new java.awt.Color(255, 102, 102));
        jLabelUserName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUserName7.setText("Categoria");

        jTextFieldUser10.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUser10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser10.setText(" ");
        jTextFieldUser10.setToolTipText("");
        jTextFieldUser10.setAutoscrolls(false);
        jTextFieldUser10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUser10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUser10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUser10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelUserName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUser1)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jLabelUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUser5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUser4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBodyLayout.createSequentialGroup()
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUserName4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUser9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUserName5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldUser2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldUser3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPass1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jLabelPass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName1)
                    .addComponent(jLabelUserName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName3)
                    .addComponent(jLabelUserName4)
                    .addComponent(jLabelUserName5))
                .addGap(10, 10, 10)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUser10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalmxLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addComponent(jLabelSalmxLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser1ActionPerformed

    private void jTextFieldUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser3ActionPerformed

    private void jTextFieldUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser4ActionPerformed

    private void jTextFieldUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser5ActionPerformed

    private void jTextFieldUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser6ActionPerformed

    private void jTextFieldUser7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser7ActionPerformed

    private void jTextFieldUser8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser8ActionPerformed

    private void jTextFieldUser9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser9ActionPerformed

    private void jTextFieldUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser2ActionPerformed

    private void jTextFieldUser10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUser10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUser10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFornecedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFornecedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFornecedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFornecedorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFornecedorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPass1;
    private javax.swing.JLabel jLabelSalmxLogo;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserName1;
    private javax.swing.JLabel jLabelUserName2;
    private javax.swing.JLabel jLabelUserName3;
    private javax.swing.JLabel jLabelUserName4;
    private javax.swing.JLabel jLabelUserName5;
    private javax.swing.JLabel jLabelUserName6;
    private javax.swing.JLabel jLabelUserName7;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField jTextFieldUser1;
    private javax.swing.JTextField jTextFieldUser10;
    private javax.swing.JTextField jTextFieldUser2;
    private javax.swing.JTextField jTextFieldUser3;
    private javax.swing.JTextField jTextFieldUser4;
    private javax.swing.JTextField jTextFieldUser5;
    private javax.swing.JTextField jTextFieldUser6;
    private javax.swing.JTextField jTextFieldUser7;
    private javax.swing.JTextField jTextFieldUser8;
    private javax.swing.JTextField jTextFieldUser9;
    // End of variables declaration//GEN-END:variables
}
