/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Materiais.view;

import javax.swing.*;

/**
 *
 * @author jimmy
 */
public class EntradaItem extends javax.swing.JDialog {

    /**
     * Creates new form EntradaItem
     */
    public EntradaItem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JLabel getJLabelSalvar() {
        return JLabelSalvar;
    }

    public void setJLabelSalvar(JLabel JLabelSalvar) {
        this.JLabelSalvar = JLabelSalvar;
    }

    public JTextField getJTextFieldEmpenho() {
        return JTextFieldEmpenho;
    }

    public void setJTextFieldEmpenho(JTextField JTextFieldEmpenho) {
        this.JTextFieldEmpenho = JTextFieldEmpenho;
    }

    public JTextField getJTextFieldNotaFiscal() {
        return JTextFieldNotaFiscal;
    }

    public void setJTextFieldNotaFiscal(JTextField JTextFieldNotaFiscal) {
        this.JTextFieldNotaFiscal = JTextFieldNotaFiscal;
    }

    public JTextField getJTextFieldPrec_Unit() {
        return JTextFieldPrec_Unit;
    }

    public void setJTextFieldPrec_Unit(JTextField JTextFieldPrec_Unit) {
        this.JTextFieldPrec_Unit = JTextFieldPrec_Unit;
    }

    public JTextField getJTextFieldQuantid() {
        return JTextFieldQuantid;
    }

    public void setJTextFieldQuantid(JTextField JTextFieldQuantid) {
        this.JTextFieldQuantid = JTextFieldQuantid;
    }

    public JTextField getJTextFieldcodigo() {
        return JTextFieldcodigo;
    }

    public void setJTextFieldcodigo(JTextField JTextFieldcodigo) {
        this.JTextFieldcodigo = JTextFieldcodigo;
    }

    public JComboBox getjComboCategoria() {
        return jComboCategoria;
    }

    public void setjComboCategoria(JComboBox jComboCategoria) {
        this.jComboCategoria = jComboCategoria;
    }

    public JComboBox getjComboFornecedor() {
        return jComboFornecedor;
    }

    public void setjComboFornecedor(JComboBox jComboFornecedor) {
        this.jComboFornecedor = jComboFornecedor;
    }

    public JComboBox getjComboItem() {
        return jComboItem;
    }

    public void setjComboItem(JComboBox jComboItem) {
        this.jComboItem = jComboItem;
    }

    public JScrollPane getjObservacao() {
        return jObservacao;
    }

    public void setjObservacao(JScrollPane jObservacao) {
        this.jObservacao = jObservacao;
    }

    public JFormattedTextField getjTextFieldDt_Validade() {
        return jTextFieldDt_Validade;
    }

    public void setjTextFieldDt_Validade(JFormattedTextField jTextFieldDt_Validade) {
        this.jTextFieldDt_Validade = jTextFieldDt_Validade;
    }

    public JFormattedTextField getjTextFieldDt_compra() {
        return jTextFieldDt_compra;
    }

    public void setjTextFieldDt_compra(JFormattedTextField jTextFieldDt_compra) {
        this.jTextFieldDt_compra = jTextFieldDt_compra;
    }

    public JFormattedTextField getjTextFieldPrc_Total() {
        return jTextFieldPrc_Total;
    }

    public void setjTextFieldPrc_Total(JFormattedTextField jTextFieldPrc_Total) {
        this.jTextFieldPrc_Total = jTextFieldPrc_Total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBack = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelSalmxLogo = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jComboCategoria = new javax.swing.JComboBox();
        jComboItem = new javax.swing.JComboBox();
        jComboFornecedor = new javax.swing.JComboBox();
        JTextFieldNotaFiscal = new javax.swing.JTextField();
        JLabelEmpenho = new javax.swing.JLabel();
        JLabelFornecedor = new javax.swing.JLabel();
        JLabelCategoria = new javax.swing.JLabel();
        JLabelItem = new javax.swing.JLabel();
        JLabelSalvar = new javax.swing.JLabel();
        JLabel1 = new javax.swing.JLabel();
        JTextFieldPrec_Unit = new javax.swing.JTextField();
        jTextFieldDt_compra = new javax.swing.JFormattedTextField();
        JLabel2 = new javax.swing.JLabel();
        JTextFieldcodigo = new javax.swing.JTextField();
        JLabel3 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        jTextFieldPrc_Total = new javax.swing.JFormattedTextField();
        JLabelNF = new javax.swing.JLabel();
        JTextFieldEmpenho = new javax.swing.JTextField();
        JLabel6 = new javax.swing.JLabel();
        jTextFieldDt_Validade = new javax.swing.JFormattedTextField();
        JLabel4 = new javax.swing.JLabel();
        JTextFieldQuantid = new javax.swing.JTextField();
        JLabel7 = new javax.swing.JLabel();
        jObservacao = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntradas = new javax.swing.JTable();
        JLabelEdit = new javax.swing.JLabel();
        JLabelAdd1 = new javax.swing.JLabel();
        JLabelDel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBack.setBackground(new java.awt.Color(247, 247, 247));

        jPanelTop.setBackground(new java.awt.Color(255, 102, 102));

        jLabelSalmxLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSalmxLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalmxLogoPequeno.png"))); // NOI18N
        jLabelSalmxLogo.setText(" ");
        jLabelSalmxLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalmxLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalmxLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanelBody.setBackground(new java.awt.Color(242, 242, 242));

        jComboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCategoria.setOpaque(false);
        jComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaActionPerformed(evt);
            }
        });

        jComboItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboItem.setOpaque(false);
        jComboItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboItemActionPerformed(evt);
            }
        });

        jComboFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboFornecedor.setOpaque(false);
        jComboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFornecedorActionPerformed(evt);
            }
        });

        JTextFieldNotaFiscal.setForeground(new java.awt.Color(153, 153, 153));
        JTextFieldNotaFiscal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFieldNotaFiscal.setToolTipText("");
        JTextFieldNotaFiscal.setAutoscrolls(false);
        JTextFieldNotaFiscal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTextFieldNotaFiscal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextFieldNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldNotaFiscalActionPerformed(evt);
            }
        });

        JLabelEmpenho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelEmpenho.setForeground(new java.awt.Color(255, 102, 102));
        JLabelEmpenho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelEmpenho.setText("Nº do Empenho *");

        JLabelFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelFornecedor.setForeground(new java.awt.Color(255, 102, 102));
        JLabelFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelFornecedor.setText("Fornecedor*");

        JLabelCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelCategoria.setForeground(new java.awt.Color(255, 102, 102));
        JLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelCategoria.setText("Categoria*");

        JLabelItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelItem.setForeground(new java.awt.Color(255, 102, 102));
        JLabelItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelItem.setText("Item*");

        JLabelSalvar.setBackground(new java.awt.Color(255, 102, 102));
        JLabelSalvar.setForeground(new java.awt.Color(255, 255, 255));
        JLabelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelSalvar.setText("SALVAR");
        JLabelSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabelSalvar.setOpaque(true);

        JLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(255, 102, 102));
        JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel1.setText("Preço Unt.*");

        JTextFieldPrec_Unit.setForeground(new java.awt.Color(153, 153, 153));
        JTextFieldPrec_Unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFieldPrec_Unit.setToolTipText("");
        JTextFieldPrec_Unit.setAutoscrolls(false);
        JTextFieldPrec_Unit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTextFieldPrec_Unit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextFieldPrec_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldPrec_UnitActionPerformed(evt);
            }
        });

        jTextFieldDt_compra.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldDt_compra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jTextFieldDt_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDt_compraActionPerformed(evt);
            }
        });

        JLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(255, 102, 102));
        JLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel2.setText("Quantidade");

        JTextFieldcodigo.setForeground(new java.awt.Color(153, 153, 153));
        JTextFieldcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFieldcodigo.setToolTipText("");
        JTextFieldcodigo.setAutoscrolls(false);
        JTextFieldcodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTextFieldcodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextFieldcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldcodigoActionPerformed(evt);
            }
        });

        JLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(255, 102, 102));
        JLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel3.setText("Preço total");

        JLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel5.setForeground(new java.awt.Color(255, 102, 102));
        JLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel5.setText("Data de compra *");

        jTextFieldPrc_Total.setBorder(null);
        jTextFieldPrc_Total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        JLabelNF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelNF.setForeground(new java.awt.Color(255, 102, 102));
        JLabelNF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelNF.setText("Nº da Nota Fiscal*");

        JTextFieldEmpenho.setForeground(new java.awt.Color(153, 153, 153));
        JTextFieldEmpenho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFieldEmpenho.setToolTipText("");
        JTextFieldEmpenho.setAutoscrolls(false);
        JTextFieldEmpenho.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTextFieldEmpenho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextFieldEmpenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldEmpenhoActionPerformed(evt);
            }
        });

        JLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel6.setForeground(new java.awt.Color(255, 102, 102));
        JLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel6.setText("Data de validade *");

        jTextFieldDt_Validade.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldDt_Validade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jTextFieldDt_Validade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDt_ValidadeActionPerformed(evt);
            }
        });

        JLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel4.setForeground(new java.awt.Color(255, 102, 102));
        JLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel4.setText("codigo-entrada");

        JTextFieldQuantid.setForeground(new java.awt.Color(153, 153, 153));
        JTextFieldQuantid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFieldQuantid.setToolTipText("");
        JTextFieldQuantid.setAutoscrolls(false);
        JTextFieldQuantid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTextFieldQuantid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextFieldQuantid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldQuantidActionPerformed(evt);
            }
        });

        JLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabel7.setForeground(new java.awt.Color(255, 102, 102));
        JLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabel7.setText("Observacao");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jObservacao.setViewportView(jTextArea1);

        jTableEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "descricao", "quantidade", "preco_unitario", "observacao"
            }
        ));
        jScrollPane1.setViewportView(jTableEntradas);

        JLabelEdit.setBackground(new java.awt.Color(255, 102, 102));
        JLabelEdit.setForeground(new java.awt.Color(255, 255, 255));
        JLabelEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelEdit.setText("Editar");
        JLabelEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabelEdit.setOpaque(true);

        JLabelAdd1.setBackground(new java.awt.Color(255, 102, 102));
        JLabelAdd1.setForeground(new java.awt.Color(255, 255, 255));
        JLabelAdd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelAdd1.setText("Adicionar");
        JLabelAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabelAdd1.setOpaque(true);

        JLabelDel.setBackground(new java.awt.Color(255, 102, 102));
        JLabelDel.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelDel.setText("Remover");
        JLabelDel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabelDel.setOpaque(true);

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(JLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jObservacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBodyLayout.createSequentialGroup()
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JLabelEmpenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBodyLayout.createSequentialGroup()
                                        .addComponent(JTextFieldPrec_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTextFieldQuantid))
                                    .addComponent(JLabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBodyLayout.createSequentialGroup()
                                        .addComponent(JLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(JLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                    .addComponent(JTextFieldEmpenho, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTextFieldNotaFiscal)
                                            .addComponent(jComboItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLabelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLabelNF, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrc_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldDt_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JLabelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTextFieldcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDt_Validade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(JLabelAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JLabelDel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelItem)
                    .addComponent(JLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelEmpenho)
                    .addComponent(JLabelNF)
                    .addComponent(JLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDt_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel1)
                    .addComponent(JLabel2)
                    .addComponent(JLabel3)
                    .addComponent(JLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldPrec_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrc_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldQuantid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDt_Validade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel7)
                    .addComponent(JLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addComponent(JTextFieldcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(JLabelAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(jObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGap(11, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(JLabelSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBodyLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(JLabelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(JLabelDel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JTextFieldNotaFiscal, JTextFieldPrec_Unit, JTextFieldcodigo, jComboCategoria, jComboFornecedor, jComboItem});

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCategoriaActionPerformed

    private void jComboItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboItemActionPerformed

    private void jComboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFornecedorActionPerformed

    private void JTextFieldNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldNotaFiscalActionPerformed

    private void JTextFieldPrec_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldPrec_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldPrec_UnitActionPerformed

    private void jTextFieldDt_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDt_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDt_compraActionPerformed

    private void JTextFieldcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldcodigoActionPerformed

    private void JTextFieldEmpenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldEmpenhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldEmpenhoActionPerformed

    private void jTextFieldDt_ValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDt_ValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDt_ValidadeActionPerformed

    private void JTextFieldQuantidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldQuantidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldQuantidActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel JLabelAdd1;
    private javax.swing.JLabel JLabelCategoria;
    private javax.swing.JLabel JLabelDel;
    private javax.swing.JLabel JLabelEdit;
    private javax.swing.JLabel JLabelEmpenho;
    private javax.swing.JLabel JLabelFornecedor;
    private javax.swing.JLabel JLabelItem;
    private javax.swing.JLabel JLabelNF;
    private javax.swing.JLabel JLabelSalvar;
    private javax.swing.JTextField JTextFieldEmpenho;
    private javax.swing.JTextField JTextFieldNotaFiscal;
    private javax.swing.JTextField JTextFieldPrec_Unit;
    private javax.swing.JTextField JTextFieldQuantid;
    private javax.swing.JTextField JTextFieldcodigo;
    private javax.swing.JComboBox jComboCategoria;
    private javax.swing.JComboBox jComboFornecedor;
    private javax.swing.JComboBox jComboItem;
    private javax.swing.JLabel jLabelSalmxLogo;
    private javax.swing.JScrollPane jObservacao;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEntradas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JFormattedTextField jTextFieldDt_Validade;
    private javax.swing.JFormattedTextField jTextFieldDt_compra;
    private javax.swing.JFormattedTextField jTextFieldPrc_Total;
    // End of variables declaration//GEN-END:variables
}
