package Principal.IconesTelaV2;

import Materiais.view.MateriaisFrame;
import Usuarios.view.LoginFrame;
import Usuarios.view.UserFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jimmy
 */
public class MainFrameV2 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameV2
     */
    public MainFrameV2() {
      new LoginFrame().setVisible(true);     
       initComponents();     
    }
     public MainFrameV2(boolean op) {
      this.setVisible(op);     
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBackground = new javax.swing.JPanel();
        JPanelTop = new javax.swing.JPanel();
        Salmx_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        JPanelBody = new javax.swing.JPanel();
        Fornecedores_Icone = new javax.swing.JLabel();
        Fornecedores_Label = new javax.swing.JLabel();
        Categorias_Icone = new javax.swing.JLabel();
        Categorias_Label = new javax.swing.JLabel();
        Materiais_Icone = new javax.swing.JLabel();
        Materias_Label = new javax.swing.JLabel();
        Usuarios_Icone = new javax.swing.JLabel();
        Usuarios_Label = new javax.swing.JLabel();
        Relatorios_Icone = new javax.swing.JLabel();
        Relatorios_Label = new javax.swing.JLabel();
        Setores_Icone = new javax.swing.JLabel();
        Setores_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        JPanelBackground.setBackground(new java.awt.Color(255, 255, 255));

        JPanelTop.setBackground(new java.awt.Color(255, 102, 102));
        JPanelTop.setPreferredSize(new java.awt.Dimension(678, 30));

        Salmx_Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Salmx_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalmxLogo.png"))); // NOI18N
        Salmx_Logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserGrey.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabelLogout.setBackground(new java.awt.Color(102, 102, 102));
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogout.setText("LOGOUT");
        jLabelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelLogout.setOpaque(true);

        javax.swing.GroupLayout JPanelTopLayout = new javax.swing.GroupLayout(JPanelTop);
        JPanelTop.setLayout(JPanelTopLayout);
        JPanelTopLayout.setHorizontalGroup(
            JPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTopLayout.createSequentialGroup()
                .addComponent(Salmx_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addGroup(JPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelTopLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelTopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );

        JPanelTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabelLogout});

        JPanelTopLayout.setVerticalGroup(
            JPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salmx_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(JPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JPanelBody.setBackground(new java.awt.Color(255, 255, 255));

        Fornecedores_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Fornecedores_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Fornecedores_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fornecedores_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Fornecedores.png"))); // NOI18N
        Fornecedores_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Fornecedores_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Fornecedores_Icone.setMaximumSize(null);
        Fornecedores_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Fornecedores_Icone.setOpaque(true);
        Fornecedores_Icone.setPreferredSize(new java.awt.Dimension(150, 150));

        Fornecedores_Label.setBackground(new java.awt.Color(255, 255, 255));
        Fornecedores_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Fornecedores_Label.setForeground(new java.awt.Color(153, 153, 153));
        Fornecedores_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fornecedores_Label.setText("FORNECEDORES");
        Fornecedores_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Fornecedores_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        Categorias_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Categorias_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Categorias_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Categorias_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Categorias.png"))); // NOI18N
        Categorias_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Categorias_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Categorias_Icone.setMaximumSize(null);
        Categorias_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Categorias_Icone.setOpaque(true);
        Categorias_Icone.setPreferredSize(new java.awt.Dimension(150, 150));

        Categorias_Label.setBackground(new java.awt.Color(255, 255, 255));
        Categorias_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Categorias_Label.setForeground(new java.awt.Color(153, 153, 153));
        Categorias_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Categorias_Label.setText("CATEGORIAS");
        Categorias_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Categorias_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        Materiais_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Materiais_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Materiais_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Materiais_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Produtos.png"))); // NOI18N
        Materiais_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Materiais_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Materiais_Icone.setMaximumSize(null);
        Materiais_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Materiais_Icone.setOpaque(true);
        Materiais_Icone.setPreferredSize(new java.awt.Dimension(150, 150));
        Materiais_Icone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Materiais_IconeMouseClicked(evt);
            }
        });

        Materias_Label.setBackground(new java.awt.Color(255, 255, 255));
        Materias_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Materias_Label.setForeground(new java.awt.Color(153, 153, 153));
        Materias_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Materias_Label.setText("MATERIAIS");
        Materias_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Materias_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        Usuarios_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Usuarios_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Usuarios_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuarios_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Usuarios.png"))); // NOI18N
        Usuarios_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Usuarios_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuarios_Icone.setMaximumSize(null);
        Usuarios_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Usuarios_Icone.setOpaque(true);
        Usuarios_Icone.setPreferredSize(new java.awt.Dimension(150, 150));
        Usuarios_Icone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Usuarios_IconeMouseClicked(evt);
            }
        });

        Usuarios_Label.setBackground(new java.awt.Color(255, 255, 255));
        Usuarios_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Usuarios_Label.setForeground(new java.awt.Color(153, 153, 153));
        Usuarios_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuarios_Label.setText("USUÁRIOS");
        Usuarios_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Usuarios_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        Relatorios_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Relatorios_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Relatorios_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Relatorios_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Relatorios.png"))); // NOI18N
        Relatorios_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Relatorios_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Relatorios_Icone.setMaximumSize(null);
        Relatorios_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Relatorios_Icone.setOpaque(true);
        Relatorios_Icone.setPreferredSize(new java.awt.Dimension(150, 150));

        Relatorios_Label.setBackground(new java.awt.Color(255, 255, 255));
        Relatorios_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Relatorios_Label.setForeground(new java.awt.Color(153, 153, 153));
        Relatorios_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Relatorios_Label.setText("RELATÓRIOS");
        Relatorios_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Relatorios_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        Setores_Icone.setBackground(new java.awt.Color(249, 249, 249));
        Setores_Icone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Setores_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Setores_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/IconesTelaV2/Setores.png"))); // NOI18N
        Setores_Icone.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Setores_Icone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Setores_Icone.setMaximumSize(null);
        Setores_Icone.setMinimumSize(new java.awt.Dimension(120, 120));
        Setores_Icone.setOpaque(true);
        Setores_Icone.setPreferredSize(new java.awt.Dimension(150, 150));

        Setores_Label.setBackground(new java.awt.Color(255, 255, 255));
        Setores_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Setores_Label.setForeground(new java.awt.Color(153, 153, 153));
        Setores_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Setores_Label.setText("SETORES");
        Setores_Label.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Setores_Label.setMaximumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout JPanelBodyLayout = new javax.swing.GroupLayout(JPanelBody);
        JPanelBody.setLayout(JPanelBodyLayout);
        JPanelBodyLayout.setHorizontalGroup(
            JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBodyLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Fornecedores_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(Fornecedores_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Setores_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Setores_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Categorias_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Categorias_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(Relatorios_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Relatorios_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Materiais_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Materias_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(Usuarios_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Usuarios_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        JPanelBodyLayout.setVerticalGroup(
            JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBodyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Categorias_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Fornecedores_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Materiais_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fornecedores_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Categorias_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Materias_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Setores_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Relatorios_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Usuarios_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relatorios_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuarios_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Setores_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout JPanelBackgroundLayout = new javax.swing.GroupLayout(JPanelBackground);
        JPanelBackground.setLayout(JPanelBackgroundLayout);
        JPanelBackgroundLayout.setHorizontalGroup(
            JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addComponent(JPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanelBackgroundLayout.setVerticalGroup(
            JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                .addComponent(JPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usuarios_IconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usuarios_IconeMouseClicked
        new UserFrame().setVisible(true);
    }//GEN-LAST:event_Usuarios_IconeMouseClicked

    private void Materiais_IconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Materiais_IconeMouseClicked
       
        new MateriaisFrame().setVisible(true);
    }//GEN-LAST:event_Materiais_IconeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categorias_Icone;
    private javax.swing.JLabel Categorias_Label;
    private javax.swing.JLabel Fornecedores_Icone;
    private javax.swing.JLabel Fornecedores_Label;
    private javax.swing.JPanel JPanelBackground;
    private javax.swing.JPanel JPanelBody;
    private javax.swing.JPanel JPanelTop;
    private javax.swing.JLabel Materiais_Icone;
    private javax.swing.JLabel Materias_Label;
    private javax.swing.JLabel Relatorios_Icone;
    private javax.swing.JLabel Relatorios_Label;
    private javax.swing.JLabel Salmx_Logo;
    private javax.swing.JLabel Setores_Icone;
    private javax.swing.JLabel Setores_Label;
    private javax.swing.JLabel Usuarios_Icone;
    private javax.swing.JLabel Usuarios_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogout;
    // End of variables declaration//GEN-END:variables
}
